#pragma kernel InitializeParticles

struct Particle {
    float3 position;
};

RWStructuredBuffer<Particle> _ParticlesBuffer;

float _GraphScaling;
int _Dimension;
float _Size;

[numthreads(8,8,1)]
void InitializeParticles(uint3 id : SV_DispatchThreadID) {
    if (id.x < _Dimension && id.y < _Dimension) {
        float3 pos = 0;
        pos.xz = id.xy * _GraphScaling * _Size;
        _ParticlesBuffer[id.x + id.y * _Dimension].position = pos;
    }
}
